language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - 7.3

sudo: true

cache:
    directories:
        - $HOME/.composer/cache/files

before_install:
    - composer self-update
    - if [ "$STABILITY" = "dev" ]; then composer config minimum-stability dev; fi;
    - if [ "$SYMFONY_VERSION" != "" ]; then COMPOSER_MEMORY_LIMIT=-1 composer require symfony/symfony:${SYMFONY_VERSION}; fi;
    - sudo chmod -R 777 Tests
    - sudo chown -R $USER Tests

install:
    - COMPOSER_MEMORY_LIMIT=-1 composer install $COMPOSER_FLAGS --prefer-dist --no-interaction

script:
    - vendor/bin/phpunit --coverage-text
    - phantomjs Resources/js/run-qunit.js file://`pwd`/Resources/js/index.html
    - phantomjs Resources/js/run-qunit.js file://`pwd`/Resources/js/index-with-es5-shim.html

matrix:
    fast_finish: true
    include:
      - php: 5.4
        dist: precise
      - php: 5.5
        dist: precise
      - php: 5.6
        env: SYMFONY_VERSION='~2.7.0'
      - php: 5.6
        env: SYMFONY_VERSION='~2.8.0'
        dist: precise
      - php: 5.6
        env: SYMFONY_VERSION='~3.4.0'
        dist: precise
      - php: 7.2
        env: SYMFONY_VERSION='~4.1.0'
      - php: 7.2
        env: SYMFONY_VERSION='~4.2.0'
      - php: 7.2
        env: STABILITY=dev
      - php: 7.3
        env: STABILITY=dev
